### ISSUE TITLE
Acurracy is pretty low

### ISSUE THREAD

**Issue by Narla-Venkata-Anand-Sai-Kumar** [Martlgap/FaceIDLight#235]
face bounding detections are inaccurate and cannot able to extract features from some images, and why the models are downloading everytime 

try to fix this

**Comment by Martlgap** [comment]
Hi, it's not the best face detection implemented here. It can happen that it does not detect a face. The models should only download ones. The code is checking the hash of the model in case it is changed and then downloads again. Something is happening with your downloaded model if the models are downloaded again everytime. 

I just updated to Python 3.9. Maybe check again.
